import telnetlib
#IOS edge switch
tn = telnetlib.Telnet("localhost", port = 5002)
tn.write(b"\n")
tn.read_until(b"R")
tn.write(b"conf t\n")
tn.read_until(b"R")
tn.write(b"username cisco privilege 15 password cisco\n")
tn.read_until(b"R")
tn.write(b"ip domain-name oefen.lab\n")
tn.read_until(b"R")
tn.write(b"crypto key generate rsa mod 2048\n")
tn.read_until(b"R")
tn.write(b"line vty 0 4\n")
tn.read_until(b"R")
tn.write(b"login local\n")
tn.read_until(b"R")
tn.write(b"transport input ssh telnet\n")
tn.read_until(b"R")
tn.write(b"exit\n")
tn.read_until(b"R")
tn.write(b"ip scp server enable\n")
tn.read_until(b"R")
tn.write(b"archive\n")
tn.read_until(b"R")
tn.write(b"path flash:archive\n")
tn.read_until(b"R")
tn.write(b"end\n")
tn.read_until(b"R")
tn.write(b"exit\n")
print(tn.read_all().decode('ascii'))