---
- name: "Test Netbox modules"
  connection: network_cli
  hosts: ESW01:ESW02
  gather_facts: true
  tasks:
    - name: "TASK 100: NETBOX >> ADD DEVICE TO NETBOX"
      netbox.netbox.netbox_device:
        netbox_url: "{{ NETBOX_URL }}"
        netbox_token: "{{ NETBOX_API_KEY }}"
        data:
          name: "{{ inventory_hostname }}"
          device_type: "{{ ansible_net_model }}"
          platform: IOS  # May be able to use a filter to define in future
          serial: "{{ ansible_net_serialnum }}"
          status: Active
          device_role: "{{ device_role }}"
          site: "{{ site }}"
          custom_fields:
            code_version: "{{ ansible_net_version }}"
    - name: "TASK 110: NETBOX >> ADD INTERFACES TO NETBOX"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ NETBOX_URL }}"
        netbox_token: "{{ NETBOX_API_KEY }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.key }}"
          type: "{{ item.key | get_interface_type }}"  # Define types
          mac_address: "{{ item.value.macaddress | ansible.netcommon.hwaddr('linux') }}"
        state: present
      with_dict:
        - "{{ ansible_net_interfaces }}"
...
