---
- name: "Test Netbox modules"
  connection: network_cli
  hosts: all
  gather_facts: false
  tasks:
  - name: check the startup-config against the running-config
    cisco.ios.ios_config:
      backup: yes
      diff_against: startup
#      diff_ignore_lines:
#      - ntp clock .*
...
