---

- name: Create config using hostvars from Netbox and Jinja2 template
  connection: network_cli
  hosts: all
  gather_facts: false
  tasks:
  - name: Create diff directory
    ansible.builtin.file:
      path: ./compiled/{{ inventory_hostname }}
      state: directory
      mode: '0755'
  - name: "Generate configs using data obtained from netbox"
    template:
      src: "./templates/routers.j2"
      dest: './compiled/{{ inventory_hostname }}/running-config'
      lstrip_blocks: true
  - napalm_install_config:
      hostname: '{{ ansible_ssh_host }}'
      username: '{{ ansible_user }}'
      dev_os: '{{ ansible_network_os }}'
      password: '{{ ansible_password }}'
      config_file: './compiled/{{ inventory_hostname }}/running-config'
      #config_file: './output/{{ inventory_hostname }}.cfg'
      commit_changes: true
      replace_config: true
      get_diffs: true
      diff_file: './compiled/{{ inventory_hostname }}/diff'
      #optional_args:
      #  dest_file_system : 'disk0:/'
      
  # - name: Install Config using Provider
  #  napalm_install_config:
  #    provider: "{{ ios_provider }}"
  #    config_file: '../compiled/{{ inventory_hostname }}/running.conf'
  #    commit_changes: '{{ commit_changes }}'
  #    replace_config: '{{ replace_config }}'
  #    get_diffs: True
  #    diff_file: '../compiled/{{ inventory_hostname }}/diff'
