---

- name: Create config using hostvars from Netbox and Jinja2 template
  connection: network_cli
  hosts: R1
  gather_facts: false

  tasks:
    - name: "Generate configs using data obtained from netbox"
      template:
        src: "./templates/routers.j2"
        dest: "./output/{{ inventory_hostname }}.cfg"
        lstrip_blocks: true
    - name: check the running-config against master config
      cisco.ios.ios_config:
        diff_against: intended
        intended_config: "{{ lookup('file', './output/{{ inventory_hostname }}.cfg') }}"
