import telnetlib

tnports = {
    '192.168.13.11' : 5000,
    '192.168.13.12' : 5002,
}
for host,port in tnports.items():
    tn = telnetlib.Telnet("192.168.13.1",port)
    print(tn.read_very_eager().decode('ascii'))
    tn.write(b"\r")
    print(tn.read_very_eager().decode('ascii'))
    tn.write(b"enable\r")
    tn.read_very_eager()
    tn.write(b"terminal length 0\r")
    tn.read_very_eager()
    tn.write(b"conf t\r")
    tn.read_very_eager()
    tn.write(b"username cisco privilege 15 password cisco\r")
    tn.read_very_eager()
    tn.write(b"ip domain-name oefen.lab\r")
    tn.read_very_eager()
    tn.write(b"crypto key generate rsa mod 2048\r")
    tn.read_very_eager()
    tn.write(b"line con 0\r")
    tn.read_very_eager()
    tn.write(b"privilege level 15\r")
    tn.read_very_eager()
    tn.write(b"line vty 0 4\r")
    tn.read_very_eager()
    tn.write(b"login local\r")
    tn.read_very_eager()
    tn.write(b"transport input ssh telnet\r")
    tn.read_very_eager()
    tn.write(b"exit\r")
    tn.read_very_eager()
    tn.write(b"ip scp server enable\r")
    tn.read_very_eager()
    tn.write(b"archive\r")
    tn.read_very_eager()
    tn.write(b"path flash0:archive\r")
    tn.read_very_eager()
    tn.read_very_eager()
    tn.write(b"int vlan 1\r")
    tn.read_very_eager()
    tn.write(str.encode(f"ip address {host} 255.255.255.0\r"))
    tn.read_very_eager()
    tn.write(b"no shut\r")
    tn.read_very_eager()
    tn.write(b"end\r")